#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit "$1"
npx --no -- commitlint --edit "$1" || {
  echo "Commitlint failed. Please fix errors and try committing again.";
  exit 1;
}
